### ISSUE TITLE
Does not read temperature on esp8266_rtos_sdk

### ISSUE THREAD

**Issue by Foxi352** [aZholtikov/zh_ds18b20#1]
Hi,

I am currently converting an esp8266 Arduino IDE project to rtos_sdk.

When trying your component, it detects the DS18B20 but temperatur is empty. This is the code i currently use, but with your exact code it's the same problem. Here i just converted it to a string to use the ESP_LOG functions.
```
        uint8_t *rom = NULL;
        float temperature = 0.0;
        zh_onewire_search_rom_init();
        for (;;)
        {
            rom = zh_onewire_search_rom_next();
            if (rom == NULL)
            {
                break;
            }

            zh_ds18b20_read(rom, &temperature);

            char rom_string[24];
            char *ptr = rom_string;
            const uint8_t *rom_ptr = rom;

            for (uint8_t i = 0; i < 8; ++i)
            {
                ptr += sprintf(ptr, "%02X ", *(rom_ptr++));
            }
            ESP_LOGI(SENSOR_TAG, "Found device ROM: %s", rom_string);
            ESP_LOGI(SENSOR_TAG, "Temperature: %0.2f", temperature);
        }
```
The result:
```
I (286984) Sensor : Found device ROM: 28 13 1E 52 05 00 00 28
I (286986) Sensor : Temperature:
```
Any idea of what i could have done wrong ?

**Comment by aZholtikov** [comment]
Hi!

I don't know why, but sometimes ESP8266 doesn't display float in the port monitor. I have encountered this many times. Replace float temperature = 0.0; with int8_t temperature = 0; This should work.

P.S. This only applies to the port monitor. The temperature is always read normally.

**Comment by Foxi352** [comment]
You are right, and i found the reason. Depending on the project, the newlib is in nano mode which disables floating point numbers in printf. If you want / need floats in prints or logs, disable in menuconfig: `Component config / Newlib / Enable ‘nano’ formatting options for printf/scanf family` and i'll work.

Or convert it to string or use some other workaround...

Closing the issue as it's not component related. Thanks for the hint !
